// jellyrec-web/app/login/page.tsx
import { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import LoginForm from '@/app/ui/login-form';

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'], subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Login To JellyRec',
};

export default function LoginPage() {
  return (
    <div
      className={`${roboto.className} w-full h-screen flex justify-center items-center bg-black`}
      style={{
        backgroundImage:
          "url('https://images.pexels.com/photos/7991582/pexels-photo-7991582.jpeg')",
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        backgroundAttachment: 'fixed',
        backgroundPosition: 'center',
      }}
    >
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
        <h1 className="text-white text-center text-[5em] mb-2.5 bg-gradient-to-br from-[#610699] to-[#1ca1d8] bg-clip-text text-transparent">
          JelllyRec
        </h1>
        <p className="text-white text-center text-2xl mb-10">
          Movie Recommendation System with Jellyfin Integration
        </p>
        <div className="flex justify-center items-center flex-col">
            <LoginForm />
        </div>
      </div>

      <div className="fixed bottom-0 right-0 text-white p-1.5 bg-[rgba(0,0,0,0.5)]">
        Image Credit:{' '}
        <a href="https://www.pexels.com/photo/7991582" className="text-white">
          Tima Miroshnichenko on Pixels
        </a>
      </div>
    </div>
  );
}

// frontend/src/routes/login/+page.svelte
<script>
  import Login from "./Login.svelte";
</script>

<head>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <title>Login To JellyRec</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #000;
            font-family: 'Roboto', sans-serif;
        }
        #center-pane {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
        #title{
            color: #fff;
            text-align: center;
            font-size: 5em;
            background: linear-gradient(135deg, #610699, #1CA1D8);
            -webkit-background-clip: text;
            color: transparent;
            margin-bottom: 10px;
        }
        #short-desc{
            color: #fff;
            text-align: center;
            font-size: 1.5em;
            margin-bottom: 40px;
        }
        #img-credit {
            position: fixed;
            bottom: 0;
            right: 0;
            color: #fff;
            text-decoration: none;
            padding: 5px;
            background: rgba(0, 0, 0, 0.5)
        }
        #img-credit a {
            color: #fff;
        }
        #login-pane {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }
    </style>
</head>

<body style="background-image: url('https://images.pexels.com/photos/7991582/pexels-photo-7991582.jpeg'); background-size: cover; background-repeat: no-repeat; background-attachment: fixed; background-position: center;">
    <div id="center-pane">
        <h1 id="title">JelllyRec</h1>
        <p id="short-desc">Movie Recommendation System with Jellyfin Integration</p>
        <div id="login-pane"><Login /></div>
    </div>

    <div id="img-credit">
        Image Credit: <a href="https://www.pexels.com/photo/7991582">Tima Miroshnichenko on Pixels</a>
    </div>
</body>
